[package]
name = "renegade_contracts"
version = "0.1.0"

[[target.starknet-contract]]
allowed-libfuncs-list = { name = "experimental" }
casm = true
casm-add-pythonic-hints = true

[dependencies]
starknet = "=2.1.1"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "b519245" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "b519245" }
alexandria_linalg = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "b519245" }
