name: Formatting

on: pull_request

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-06-02
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.0.1
        with:
          scarb-version: "0.6.2"

      - name: Check Cairo formatting
        run: scarb fmt --check

      - name: Check Rust formatting
        run: cargo fmt --check
      