name: Devnet Tests

on: pull_request

jobs:
  test_devnet:
    name: test_devnet
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-06-02

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.0.1
        with:
          scarb-version: "0.6.2"

      - name: Build Cairo
        run: scarb -P release build

      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          ARTIFACTS_PATH: ${{ github.workspace }}/target/release
          RUST_LOG: "tests=debug,katana_core=warn"
          CAIRO_STEP_LIMIT: 10000000
        with:
          command: test
          args: -p tests --all-targets --lib --verbose -- --nocapture
