name: Cairo Tests

on: pull_request

jobs:
  test_cairo:
    name: test_cairo
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.0.1
        with:
          scarb-version: "0.6.2"

      - name: Run Cairo tests
        run: scarb test
